env:
  contexts:
  - name: AwesomeToDo
    urls:
    - http://localhost:8000
    includePaths:
    - http://localhost:8000.*
    authentication:
      verification:
        method: response
        pollFrequency: 60
        pollUnits: requests
        pollUrl: ""
        pollPostData: ""
    sessionManagement:
      method: cookie
    technology: {}
    structure: {}
  parameters: {}
jobs:
- type: passiveScan-config
  parameters: {}
- name: import HAR file
  type: import
  parameters:
    type: har
    fileName: /root/AwesomeToDo/tmp/AwesomeToDo.har
- type: passiveScan-wait
  parameters: {}
- type: activeScan
  parameters:
    context: AwesomeToDo
    user: ""
    policy: ""
    maxRuleDurationInMins: 0
    maxScanDurationInMins: 0
    maxAlertsPerRule: 0
  policyDefinition:
    defaultStrength: medium
    defaultThreshold: medium
- type: report
  parameters:
    template: risk-confidence-html
    theme: original
    reportDir: /root
    reportFile: ZAP_Report
    reportTitle: ZAP Scanning Report
    reportDescription: ""
    displayReport: false
  risks:
  - info
  - low
  - medium
  - high
  confidences:
  - falsepositive
  - low
  - medium
  - high
  - confirmed
  sections:
  - siteRiskCounts
  - responseBody
  - appendix
  - alertTypes
  - responseHeader
  - alertTypeCounts
  - riskConfidenceCounts
  - alerts
  - aboutThisReport
  - contents
  - requestBody
  - reportDescription
  - reportParameters
  - requestHeader
  - summaries

