name: Docker

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
        contents: read  # リポジトリのコードを取得できるようにする
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    # 2. Dockerイメージのビルド
    - name: Build Docker image
      run: docker build -t awesometodo:latest .

    # 3. Docker Composeのセットアップ
    - name: Set up Docker Compose
      run: docker compose up -d

    # 4. Composer依存関係をインストール
    - name: Install Composer dependencies
      run: docker compose exec app composer install
    
    # 5. DB権限設定
    - name: chmod and chown
      run: |
        docker compose exec app chmod 640 /var/www/data/db/todo.db
        docker compose exec app chmod 750 /var/www/data/db
        docker compose exec app chown www-data:www-data /var/www/data/db
        docker compose exec app chown www-data:www-data /var/www/data/db/todo.db
    
    # 6. PHPUnitテストの実行
    - name: Run PHPUnit tests
      run: docker compose exec app ./vendor/bin/phpunit --configuration phpunit.xml

