name: Docker

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    # 1. ソースコードをチェックアウト
    - name: Checkout code
      uses: actions/checkout@v4

    # 2. Dockerイメージのビルド
    - name: Build Docker image
      run: docker build -t awesometodo:latest .

    # 3. Docker Composeのセットアップ
    - name: Set up Docker Compose
      run: docker compose up -d

    # 4. Composer依存関係をインストール
    - name: Install Composer dependencies
      run: docker compose exec app composer install

    - name: Curl test
      run: |
        curl -X POST -H "Content-Type: application/json" -d '{\"title\": \"Test ToDo\", \"due_date\": \"2025-12-31 23:59:59\"}' http://nginx-server/api/todo.php?action=add
    
    # 5. PHPUnitテストの実行
    - name: Run PHPUnit tests
      run: docker compose exec app ./vendor/bin/phpunit --configuration phpunit.xml

