name: Docker

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    # 1. ソースコードをチェックアウト
    - name: Checkout code
      uses: actions/checkout@v4

    # 2. Dockerイメージのビルド
    - name: Build Docker image
      run: docker build -t awesometodo:latest .

    # 3. Docker Composeのセットアップ
    - name: Set up Docker Compose
      run: docker compose up -d

    # 4. Composer依存関係をインストール
    - name: Install Composer dependencies
      run: docker compose exec app composer install

    # 5. PHPUnitテストの実行
    - name: Run PHPUnit tests
      run: docker compose exec app ./vendor/bin/phpunit --configuration phpunit.xml

    - name: nginx log check
      run: docker compose exec nginx tail -f /var/log/nginx/error.log
    - name: php log check
      run: docker compose exec app tail -f /var/log/php_errors.log

