name: Docker Build and Push with Compose

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    steps:
    - name: "Checkout code"
      uses: actions/checkout@v4

    - name: "Login to GHCR"
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: "Create metadata"
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ghcr.io/securistant/awesometodo
        tags: |
          type=raw,value=latest
          type=sha,prefix=,suffix=,format=short

    - name: "Build with Docker Compose"
      run: docker-compose -f docker-compose.yml build

    - name: "Check built images"
      run: docker images

    - name: "Push Image"
      run: docker-compose -f docker-compose.yml push
