name: Docker

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    # 1. ソースコードをチェックアウト
    - name: Checkout code
      uses: actions/checkout@v4

    # 2. Dockerイメージのビルド
    - name: Build Docker image
      run: docker build -t awesometodo:latest .

    # 3. Docker Composeのセットアップ
    - name: Set up Docker Compose
      run: docker compose up -d

    # 4. Composer依存関係をインストール
    - name: Install Composer dependencies
      run: docker compose exec app composer install

    - name: Install Ping
      run: sudo apt-get update && sudo apt-get install -y curl
    - name: exec ping
      run: docker exec -it php-app ping nginx-server

    # 5. PHPUnitテストの実行
    - name: Run PHPUnit tests
      run: docker compose exec app ./vendor/bin/phpunit --configuration phpunit.xml

