name: Test
on:
    push:
        branches:
            - main
    pull_request:
jobs:
    test:
        name: PHPUnit Test
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: php-actions/composer@v6
              with:
                php_version: '8.4.3'
            - run: |
                nohup php -S 127.0.0.1:8000 > /dev/null 2>&1 &
                sleep 3
            - uses: php-actions/phpunit@v3
              with:
                php_version: '8.4.3'
                args: "-d date.timezone=Asia/Tokyo"
                configuration: phpunit.xml