name: Test
on:
    push:
        branches:
            - main
    pull_request:
jobs:
    test:
        name: PHPUnit Test
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@4
            - uses: actions/composer@v6
            with:
                php_version: '8.1'
                install_flags: '--no-progress --prefer-dist'
            - uses: actions/phpunit@v3
            with:
                php_version: '8.1'
                path: './tests/ToDoApiTest.php'